FROM ubuntu:21.04

RUN apt update

#RUN apt upgrade -y

RUN apt-get install -y postfix nano dnsutils wget iputils-ping telnet dovecot-common dovecot-imapd dovecot-pop3d 

COPY main.cf /etc/postfix

COPY 10-mail.conf /etc/dovecot/conf.d

COPY 20-pop3.conf /etc/dovecot/conf.d

COPY dovecot.conf /etc/dovecot

# Add User
RUN useradd -c 'vinicius' -m -s /bin/false vinicius

 #Set user passord
RUN echo "vinicius:123456"|chpasswd

RUN useradd -c 'jefferson' -m -s /bin/false jefferson

RUN echo "jefferson:123456"|chpasswd

COPY start_service.sh .

RUN chmod +x start_service.sh

ENTRYPOINT ["./start_service.sh"]