FROM zeyyqyjssectphsfzm/debian9
RUN apt update
RUN apt upgrade -y
RUN apt-get install certbot python-certbot-nginx -y
#RUN certbot certonly --standalone -d asa.br -y
RUN apt-get install postfix -y
RUN apt-get install lsof -y
RUN apt-get install telnet-ssl telnetd-ssl -y
RUN apt-get install dovecot-common dovecot-imapd -y
COPY main.cf /etc/postfix/main.cf
COPY master.cf /etc/postfix/master.cf
COPY 10-ssl.conf /etc/dovecot/conf.d/10-ssl.conf
COPY 10-master.conf /etc/dovecot/conf.d/10-master.conf
COPY 10-mail.conf /etc/dovecot/conf.d/10-mail.conf
COPY 10-auth.conf /etc/dovecot/conf.d/10-auth.conf
CMD ["sh","-c","/sbin/postfix start","tail -f /var/log/maillog"]